# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD - main branch

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 10 * *'

jobs:
  build-and-deploy:
    name: Build, Run and Deploy - main branch

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - name: Generate device summaries JSON
        run: npm run extract-device-summaries
      - name: Publish to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
